version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_rs
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh # Auto-init script

volumes:
  mongo_data:
